import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
const cfg=window.AICLO_CONFIG||{};
const supabase=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);
let subjects=[],selectedSubject=null,detail=null,editingPackage=null,activeMatrixScope="chapter";
let matrixDrafts={chapter:new Map(),topic:new Map()};
const esc=v=>String(v??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));
const msg=(el,text,type="")=>{el.textContent=text||"";el.className=`message ${type}`.trim();};
function busy(btn,on,label="Đang xử lý…"){if(!btn.dataset.label)btn.dataset.label=btn.textContent;btn.disabled=on;btn.textContent=on?label:btn.dataset.label;}
const normalizeCode=v=>String(v||"").trim().toUpperCase().replace(/\s+/g,"");
function localValue(iso){if(!iso)return"";const d=new Date(iso);if(Number.isNaN(d.getTime()))return"";const z=n=>String(n).padStart(2,"0");return`${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`;}
function isoValue(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString();}
async function fn(body){const {data,error}=await supabase.functions.invoke("practice-admin",{body});if(error){let text=error.message||"Lỗi máy chủ.";try{const p=await error.context?.json?.();if(p?.error)text=p.error;}catch{}throw new Error(text);}if(!data?.success)throw new Error(data?.error||"Không thể xử lý yêu cầu.");return data;}

async function restoreSession(){const {data:{session}}=await supabase.auth.getSession();if(session)showAdmin(session.user);else showLogin();}
function showLogin(){$("loginView").classList.remove("hidden");$("adminView").classList.add("hidden");}
async function showAdmin(user){$("loginView").classList.add("hidden");$("adminView").classList.remove("hidden");$("accountEmail").textContent=user?.email||"";await loadSubjects();}
async function login(){busy($("loginBtn"),true,"Đang đăng nhập…");msg($("loginMessage"),"");try{const {data,error}=await supabase.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});if(error)throw error;await showAdmin(data.user);}catch(e){msg($("loginMessage"),e.message||String(e),"error");}finally{busy($("loginBtn"),false);}}
async function logout(){await supabase.auth.signOut();subjects=[];selectedSubject=null;detail=null;showLogin();}

function renderSubjects(){const host=$("subjectList");host.innerHTML="";if(!subjects.length){host.innerHTML='<p class="muted">Chưa có môn được phân công.</p>';return;}subjects.forEach(s=>{const n=document.createElement("div");n.className=`subject-card ${selectedSubject?.id===s.id?"active":""}`;const on=!!s.practice?.is_enabled;n.innerHTML=`<div><span class="status-dot ${on?"on":""}"></span><strong>${esc(s.name)}</strong></div><div class="muted small">${esc(s.semester||"")} • ${esc(s.academic_year||"")}</div><div class="small" style="margin-top:6px">${s.practice?`Mã: <strong>${esc(s.practice.access_code)}</strong>`:"Chưa cấu hình"}</div>`;n.onclick=()=>openSubject(s);host.appendChild(n);});}
async function loadSubjects(){msg($("listMessage"),"Đang tải…");try{const d=await fn({action:"list"});subjects=d.subjects||[];msg($("listMessage"),"");renderSubjects();}catch(e){msg($("listMessage"),e.message||String(e),"error");}}
async function openSubject(subject){selectedSubject=subject;renderSubjects();$("editorCard").classList.remove("hidden");closePackageEditor();msg($("saveMessage"),"Đang tải cấu hình…");try{detail=await fn({action:"detail",subject_id:subject.id});fillEditor();msg($("saveMessage"),"");}catch(e){msg($("saveMessage"),e.message||String(e),"error");}}
function fillEditor(){const c=detail.config||{};$("editorMeta").textContent=[detail.subject.semester,detail.subject.academic_year].filter(Boolean).join(" • ");$("editorTitle").textContent=detail.subject.name;$("editorStatus").innerHTML=c.is_enabled?'<span class="status-dot on"></span><strong>Đang bật</strong>':'<span class="status-dot"></span><strong>Đang tắt</strong>';$("practiceTitleInput").value=c.title||`Đề ôn tập – ${detail.subject.name}`;$("accessCodeInput").value=c.access_code||"";$("enabledInput").checked=!!c.is_enabled;$("redrawInput").checked=c.allow_unlimited_redraw!==false;$("openAtInput").value=localValue(c.open_at);$("closeAtInput").value=localValue(c.close_at);$("statAvailable").textContent=detail.total_available||0;$("statWeek").textContent=detail.stats?.week_draws||0;$("statTotal").textContent=detail.stats?.total_draws||0;updatePublicLink();renderPackages();}
function updatePublicLink(){const code=normalizeCode($("accessCodeInput").value),url=new URL("./index.html",location.href);if(code)url.searchParams.set("code",code);$("publicLink").href=url.toString();}

async function saveConfig(){if(!selectedSubject)return;busy($("saveConfigBtn"),true,"Đang lưu…");msg($("saveMessage"),"");try{const d=await fn({action:"save_config",subject_id:selectedSubject.id,title:$("practiceTitleInput").value.trim(),access_code:normalizeCode($("accessCodeInput").value),is_enabled:$("enabledInput").checked,allow_unlimited_redraw:$("redrawInput").checked,open_at:isoValue($("openAtInput").value),close_at:isoValue($("closeAtInput").value)});detail.config=d.config;$("accessCodeInput").value=d.config.access_code;fillEditor();msg($("saveMessage"),"Đã lưu cấu hình môn.","ok");await loadSubjects();}catch(e){msg($("saveMessage"),e.message||String(e),"error");}finally{busy($("saveConfigBtn"),false);}}
async function rotateCode(){if(!selectedSubject)return;busy($("rotateCodeBtn"),true,"Đang tạo…");try{const d=await fn({action:"rotate_code",subject_id:selectedSubject.id});detail.config=d.config;$("accessCodeInput").value=d.config.access_code;updatePublicLink();msg($("saveMessage"),"Đã tạo mã mới; mã cũ hết hiệu lực ngay.","ok");await loadSubjects();}catch(e){msg($("saveMessage"),e.message||String(e),"error");}finally{busy($("rotateCodeBtn"),false);}}

function chapterMap(){return new Map((detail?.chapters||[]).map(c=>[c.id,c]));}
function topicMap(){return new Map((detail?.topics||[]).map(t=>[t.id,t]));}
function topicsOfChapter(chapterId){return(detail?.topics||[]).filter(t=>t.chapter_id===chapterId);}
function chapterNames(ids){const map=chapterMap();return(ids||[]).map(id=>map.get(id)?.name).filter(Boolean);}
function topicNames(ids){const map=topicMap();return(ids||[]).map(id=>map.get(id)?.name).filter(Boolean);}
function matrixLabel(p){if(p.draw_mode!=="matrix")return`${p.question_count} câu`;return`${p.matrix_scope==="topic"?"CLO theo Mục":"CLO theo Chương"} • ${p.question_count} câu`;}
function renderPackages(){const host=$("packageList"),packs=detail?.packages||[];host.innerHTML="";if(!packs.length){host.innerHTML='<div class="empty-box">Chưa có gói ôn tập. Bấm <strong>+ Thêm gói</strong> để tạo.</div>';return;}packs.forEach(p=>{const chapters=chapterNames(p.chapter_ids),topics=topicNames(p.topic_ids),n=document.createElement("div");n.className="package-card";n.innerHTML=`<div class="package-main"><div><span class="status-dot ${p.is_enabled?"on":""}"></span><strong>${esc(p.name)}</strong></div><div class="muted small">${esc(chapters.join(" • "))}</div><div class="muted tiny">${topics.length} Mục được chọn</div><div class="package-tags"><span>${esc(matrixLabel(p))}</span>${p.include_answers?'<span>Có đáp án</span>':''}</div></div><div class="package-actions"><button class="secondary edit">Sửa</button><button class="danger delete">Xóa</button></div>`;n.querySelector(".edit").onclick=()=>openPackageEditor(p);n.querySelector(".delete").onclick=()=>deletePackage(p);host.appendChild(n);});}

function selectedTopics(){return[...document.querySelectorAll('.topic-check:checked')].map(x=>x.value);}
function selectedChapters(){const topicIds=new Set(selectedTopics()),ids=[];for(const ch of detail?.chapters||[]){if(topicsOfChapter(ch.id).some(t=>topicIds.has(t.id)))ids.push(ch.id);}return ids;}
function matrixSnapshot(){const m=new Map();document.querySelectorAll(".matrix-input").forEach(i=>m.set(i.dataset.key,Math.max(0,Number(i.value)||0)));return m;}
function savedMatrixMap(p,scope){const m=new Map();if(!p||p.draw_mode!=="matrix"||(p.matrix_scope||"chapter")!==scope)return m;for(const x of p.matrix||[]){const key=scope==="topic"?`t:${x.topic_id}|${x.clo_id}`:`c:${x.chapter_id}|${x.clo_id}`;m.set(key,Number(x.count)||0);}return m;}
function syncChapterState(chapterId){const parent=document.querySelector(`.chapter-check[value="${chapterId}"]`),children=[...document.querySelectorAll(`.topic-check[data-chapter="${chapterId}"]`)];if(!parent)return;const n=children.filter(x=>x.checked).length;parent.checked=children.length>0&&n===children.length;parent.indeterminate=n>0&&n<children.length;}
function renderChapterPicker(selectedChapterIds=[],selectedTopicIds=[]){
 const selectedCh=new Set(selectedChapterIds),selectedTopicsSet=new Set(selectedTopicIds);let defaultFirst=!selectedChapterIds.length&&!selectedTopicIds.length;
 if(defaultFirst&&detail.chapters?.length){selectedCh.add(detail.chapters[0].id);topicsOfChapter(detail.chapters[0].id).forEach(t=>selectedTopicsSet.add(t.id));}
 if(selectedTopicIds.length===0&&selectedChapterIds.length){for(const chId of selectedCh)topicsOfChapter(chId).forEach(t=>selectedTopicsSet.add(t.id));}
 const host=$("chapterPicker");host.innerHTML=(detail.chapters||[]).map(ch=>{const topics=topicsOfChapter(ch.id),selectedCount=topics.filter(t=>selectedTopicsSet.has(t.id)).length,all=topics.length>0&&selectedCount===topics.length,partial=selectedCount>0&&!all;return`<div class="chapter-group"><label class="chapter-option"><input class="chapter-check" type="checkbox" value="${ch.id}" ${all?"checked":""} data-partial="${partial?"1":"0"}"><span><strong>${esc(ch.name)}</strong><small>${detail.chapter_availability?.[ch.id]||0} câu • ${topics.length} Mục</small></span></label><div class="topic-list">${topics.map(t=>`<label class="topic-option"><input class="topic-check" type="checkbox" value="${t.id}" data-chapter="${ch.id}" ${selectedTopicsSet.has(t.id)?"checked":""}><span>${esc(t.name)} <small>${detail.topic_counts?.[t.id]||0} câu</small></span></label>`).join("")||'<span class="muted small">Chương chưa có Mục.</span>'}</div></div>`;}).join("");
 document.querySelectorAll('.chapter-check').forEach(x=>{if(x.dataset.partial==="1")x.indeterminate=true;x.addEventListener("change",()=>{matrixDrafts[activeMatrixScope]=matrixSnapshot();document.querySelectorAll(`.topic-check[data-chapter="${x.value}"]`).forEach(t=>t.checked=x.checked);syncChapterState(x.value);buildMatrix(matrixDrafts[activeMatrixScope]);});});
 document.querySelectorAll('.topic-check').forEach(x=>x.addEventListener("change",()=>{matrixDrafts[activeMatrixScope]=matrixSnapshot();syncChapterState(x.dataset.chapter);buildMatrix(matrixDrafts[activeMatrixScope]);}));
}
function selectedTopicObjects(){const ids=new Set(selectedTopics());return(detail?.topics||[]).filter(t=>ids.has(t.id));}
function chapterCellAvailable(chapterId,cloId){return selectedTopicObjects().filter(t=>t.chapter_id===chapterId).reduce((sum,t)=>sum+(detail.topic_availability?.[`${t.id}|${cloId}`]||0),0);}
function buildMatrix(snapshot=null){
 const scope=$("matrixScopeInput").value||"chapter",clos=detail.clos||[],topics=selectedTopicObjects(),chapterIds=[...new Set(topics.map(t=>t.chapter_id))],chapters=(detail.chapters||[]).filter(c=>chapterIds.includes(c.id));
 const saved=snapshot||matrixDrafts[scope]||savedMatrixMap(editingPackage,scope);matrixDrafts[scope]=saved;
 $("matrixTitle").textContent=scope==="topic"?"Ma trận Mục × CLO":"Ma trận Chương × CLO";
 $("matrixHelp").textContent=scope==="topic"?"Mỗi Mục là một hàng; rút đúng Mục và CLO.":"CLO chung các Mục đã chọn trong từng Chương; câu có thể rút từ bất kỳ Mục đã chọn nào của Chương.";
 $("matrixHead").innerHTML=`<tr><th>${scope==="topic"?"Mục":"Chương"}</th>${clos.map(c=>`<th>${esc(c.code)}</th>`).join("")}<th>Tổng</th></tr>`;
 const rows=scope==="topic"?topics.map(t=>({id:t.id,label:`${chapterMap().get(t.chapter_id)?.name||""} · ${t.name}`,type:"topic"})):chapters.map(c=>({id:c.id,label:c.name,type:"chapter"}));
 $("matrixBody").innerHTML=rows.map(row=>`<tr data-row="${row.id}"><td><strong>${esc(row.label)}</strong></td>${clos.map(cl=>{const key=row.type==="topic"?`t:${row.id}|${cl.id}`:`c:${row.id}|${cl.id}`,have=row.type==="topic"?(detail.topic_availability?.[`${row.id}|${cl.id}`]||0):chapterCellAvailable(row.id,cl.id),val=saved.get(key)||0;return`<td><input class="matrix-input" type="number" min="0" max="${have}" value="${val}" data-key="${key}" data-scope="${row.type}" data-row="${row.id}" data-clo="${cl.id}"><span class="availability">có ${have}</span></td>`;}).join("")}<td class="row-total" data-row-total="${row.id}">0</td></tr>`).join("");
 $("matrixFoot").innerHTML=`<tr class="matrix-total-row"><th>Tổng</th>${clos.map(cl=>`<th data-clo-total="${cl.id}">0</th>`).join("")}<th id="matrixGrandTotal">0</th></tr>`;
 document.querySelectorAll(".matrix-input").forEach(i=>i.addEventListener("input",()=>{matrixDrafts[scope]=matrixSnapshot();recalcMatrix();}));recalcMatrix();
}
function recalcMatrix(){const rowTotals=new Map(),cloTotals=new Map();let total=0;document.querySelectorAll(".matrix-input").forEach(i=>{const n=Math.max(0,Number(i.value)||0);total+=n;rowTotals.set(i.dataset.row,(rowTotals.get(i.dataset.row)||0)+n);cloTotals.set(i.dataset.clo,(cloTotals.get(i.dataset.clo)||0)+n);});document.querySelectorAll("[data-row-total]").forEach(el=>el.textContent=rowTotals.get(el.dataset.rowTotal)||0);document.querySelectorAll("[data-clo-total]").forEach(el=>el.textContent=cloTotals.get(el.dataset.cloTotal)||0);$("matrixTotal").textContent=total;if($("matrixGrandTotal"))$("matrixGrandTotal").textContent=total;}
function updateMode(){const matrix=$("drawModeInput").value==="matrix";$("countField").classList.toggle("hidden",matrix);$("matrixScopeField").classList.toggle("hidden",!matrix);$("matrixSection").classList.toggle("hidden",!matrix);if(matrix)buildMatrix(matrixDrafts[$("matrixScopeInput").value]);}
function changeMatrixScope(){matrixDrafts[activeMatrixScope]=matrixSnapshot();activeMatrixScope=$("matrixScopeInput").value;buildMatrix(matrixDrafts[activeMatrixScope]);}
function openPackageEditor(p=null){editingPackage=p;matrixDrafts={chapter:new Map(),topic:new Map()};activeMatrixScope=p?.matrix_scope||"chapter";if(p?.draw_mode==="matrix")matrixDrafts[activeMatrixScope]=savedMatrixMap(p,activeMatrixScope);$("packageEditor").classList.remove("hidden");$("packageEditorTitle").textContent=p?"Sửa gói ôn tập":"Thêm gói ôn tập";$("packageNameInput").value=p?.name||"";$("packageEnabledInput").checked=p?.is_enabled!==false;$("packageAnswersInput").checked=!!p?.include_answers;$("drawModeInput").value=p?.draw_mode||"count";$("matrixScopeInput").value=activeMatrixScope;$("questionCountInput").value=p?.question_count||20;renderChapterPicker(p?.chapter_ids||[],p?.topic_ids||[]);buildMatrix(matrixDrafts[activeMatrixScope]);updateMode();msg($("packageMessage"),"");$("packageEditor").scrollIntoView({behavior:"smooth",block:"start"});}
function closePackageEditor(){editingPackage=null;matrixDrafts={chapter:new Map(),topic:new Map()};$("packageEditor").classList.add("hidden");msg($("packageMessage"),"");}
function collectMatrix(){return[...document.querySelectorAll(".matrix-input")].map(i=>{const base={clo_id:i.dataset.clo,count:Math.max(0,Number(i.value)||0)};if(i.dataset.scope==="topic")base.topic_id=i.dataset.row;else base.chapter_id=i.dataset.row;return base;}).filter(x=>x.count>0);}
async function savePackage(){if(!selectedSubject)return;const topics=selectedTopics(),chapters=selectedChapters();if(!topics.length||!chapters.length){msg($("packageMessage"),"Hãy chọn ít nhất một Chương và một Mục.","error");return;}busy($("savePackageBtn"),true,"Đang lưu…");try{await fn({action:"save_package",subject_id:selectedSubject.id,package_id:editingPackage?.id||null,name:$("packageNameInput").value.trim(),is_enabled:$("packageEnabledInput").checked,include_answers:$("packageAnswersInput").checked,chapter_ids:chapters,topic_ids:topics,draw_mode:$("drawModeInput").value,matrix_scope:$("matrixScopeInput").value,question_count:Number($("questionCountInput").value||20),matrix:collectMatrix(),sort_order:editingPackage?.sort_order??(detail.packages?.length||0)});detail=await fn({action:"detail",subject_id:selectedSubject.id});fillEditor();closePackageEditor();msg($("packageListMessage"),"Đã lưu gói ôn tập.","ok");}catch(e){msg($("packageMessage"),e.message||String(e),"error");}finally{busy($("savePackageBtn"),false);}}
async function deletePackage(p){if(!confirm(`Xóa gói “${p.name}”? Các PDF đã rút trước đây không bị ảnh hưởng.`))return;msg($("packageListMessage"),"Đang xóa…");try{await fn({action:"delete_package",subject_id:selectedSubject.id,package_id:p.id});detail=await fn({action:"detail",subject_id:selectedSubject.id});fillEditor();closePackageEditor();msg($("packageListMessage"),"Đã xóa gói ôn tập.","ok");}catch(e){msg($("packageListMessage"),e.message||String(e),"error");}}

$("loginBtn").onclick=login;$("password").addEventListener("keydown",e=>{if(e.key==="Enter")login();});$("logoutBtn").onclick=logout;$("refreshBtn").onclick=loadSubjects;$("rotateCodeBtn").onclick=rotateCode;$("saveConfigBtn").onclick=saveConfig;$("addPackageBtn").onclick=()=>openPackageEditor();$("savePackageBtn").onclick=savePackage;$("cancelPackageBtn").onclick=closePackageEditor;$("cancelPackageBtn2").onclick=closePackageEditor;$("drawModeInput").onchange=updateMode;$("matrixScopeInput").onchange=changeMatrixScope;$("accessCodeInput").addEventListener("input",()=>{$("accessCodeInput").value=normalizeCode($("accessCodeInput").value);updatePublicLink();});
restoreSession();
