import {Field} from './field.js';
const $=s=>document.querySelector(s),names='ABCDEFGHJKLMNOPQRSTUVWXYZ'.split('');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let p='3',primeCertified=true,matrices=[makeMatrix('A'),makeMatrix('B')],undo=[],history=[],last=null,pasteName='',active=null;
function makeMatrix(name,r=2,c=2){return {name,cells:Array.from({length:r},()=>Array(c).fill('0'))};}
function snapshot(){undo.push(structuredClone(matrices));if(undo.length>6)undo.shift();$('#undoButton').disabled=false;}
function checkInputSize(r,c,name=null){if(!Number.isInteger(r)||!Number.isInteger(c)||r<1||c<1||r>64||c>64||r*c>4096)throw Error('Kích thước từ 1 đến 64; mỗi ma trận tối đa 4096 ô.');const total=matrices.filter(x=>x.name!==name).reduce((s,x)=>s+x.cells.length*x.cells[0].length,0);if(total+r*c>8192)throw Error('Tổng ma trận đầu vào vượt 8192 ô.');}
function notify(message,error=false){const el=$('#status');el.hidden=false;el.className=error?'error':'';el.replaceChildren();const text=document.createElement('span');text.textContent=message;const close=document.createElement('button');close.type='button';close.textContent='Đóng';close.onclick=()=>el.hidden=true;el.append(text,close);}
function clearInvalid(){document.querySelectorAll('[aria-invalid=true]').forEach(x=>x.removeAttribute('aria-invalid'));}
function fail(e){notify(e.message||String(e),true);if(e.cell){const input=document.querySelector('[data-cell][data-name="'+e.cell.name+'"][data-row="'+e.cell.row+'"][data-col="'+e.cell.col+'"]');input?.setAttribute('aria-invalid','true');input?.focus();}else if(e.position!==undefined){$('#expression').setAttribute('aria-invalid','true');$('#expression').focus();$('#expression').setSelectionRange(e.position,e.position+1);}}
function safe(fn){return async()=>{try{await fn();}catch(e){fail(e);}};}
function matrixCard(x){const r=x.cells.length,c=x.cells[0].length;
 return `<article class="matrix-card" data-card="${x.name}"><div class="matrix-head"><h3>Ma trận ${x.name}</h3><button class="danger" data-action="delete" data-name="${x.name}" ${matrices.length===1?'disabled':''}>Xóa ${x.name}</button></div><div class="matrix-dims"><label>Dòng<input data-size="rows" data-name="${x.name}" type="number" min="1" max="64" value="${r}" aria-label="Số dòng ${x.name}"></label><label>Cột<input data-size="cols" data-name="${x.name}" type="number" min="1" max="64" value="${c}" aria-label="Số cột ${x.name}"></label><button data-action="resize" data-name="${x.name}">Đổi kích thước</button><button data-action="paste" data-name="${x.name}">Dán bảng</button></div><div class="matrix-scroll"><table class="matrix-table" aria-label="Ma trận ${x.name}"><tbody>${x.cells.map((row,i)=>'<tr>'+row.map((v,j)=>`<td><input data-cell data-name="${x.name}" data-row="${i}" data-col="${j}" value="${esc(v)}" aria-label="${x.name} dòng ${i+1} cột ${j+1}" autocomplete="off" spellcheck="false" maxlength="2000"></td>`).join('')+'</tr>').join('')}</tbody></table></div><div class="matrix-actions"><button data-action="zero" data-name="${x.name}">Không</button><button data-action="identity" data-name="${x.name}">Đơn vị</button><button data-action="random" data-name="${x.name}">Ngẫu nhiên</button><button data-action="invertible" data-name="${x.name}">Ngẫu nhiên khả nghịch</button><button data-action="normalize" data-name="${x.name}">Chuẩn hóa</button></div><div class="matrix-actions">${[['det','det'],['inv','Nghịch đảo'],['transpose','Chuyển vị'],['rank','Hạng'],['trace','Vết'],['rref','RREF']].map(([op,label])=>`<button data-expr="${op}(${x.name})">${label}</button>`).join('')}<button data-action="copy" data-name="${x.name}">Sao chép</button></div></article>`;
}
function selectors(){for(const id of ['leftMatrix','rightMatrix','resultTarget']){const select=$('#'+id),previous=select.value;select.innerHTML=matrices.map(x=>`<option>${x.name}</option>`).join('');select.value=matrices.some(x=>x.name===previous)?previous:id==='rightMatrix'&&matrices.length>1?matrices[1].name:matrices[0].name;}$('#addMatrix').disabled=matrices.length>=names.length;}
function render(){clearInvalid();$('#matrixList').innerHTML=matrices.map(matrixCard).join('');selectors();$('#undoButton').disabled=!undo.length;}
function fieldLabel(value){return 'F_'+value;}
function randomBelow(limit){if(limit===1n)return 0n;const bits=limit.toString(2).length,bytes=Math.ceil(bits/8),mask=(1<<(bits%8||8))-1;let value;do{const a=crypto.getRandomValues(new Uint8Array(bytes));a[0]&=mask;value=BigInt('0x'+[...a].map(v=>v.toString(16).padStart(2,'0')).join(''));}while(value>=limit);return value;}
function setBusy(busy){for(const id of ['calculate','runOperation','applyPrime'])$('#'+id).disabled=busy;$('#cancelJob').hidden=!busy;}
async function work(data){if(active)throw Error('Đang có tác vụ chạy. Hủy hoặc chờ tác vụ hoàn tất.');return new Promise((resolve,reject)=>{const worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});const stop=()=>{clearTimeout(timer);worker.terminate();active=null;setBusy(false);};const timer=setTimeout(()=>{stop();reject(Error('Tác vụ vượt 60 giây. Hãy giảm kích thước hoặc độ phức tạp rồi thử lại.'));},60000);active={cancel:()=>{stop();reject(Error('Đã hủy tác vụ.'));}};setBusy(true);worker.onmessage=({data:r})=>{stop();if(r.ok)resolve(r);else{const e=new Error(r.error);e.position=r.position;e.cell=r.cell;reject(e);}};worker.onerror=e=>{stop();reject(Error('Không chạy được phần tính toán: '+e.message));};worker.postMessage(data);});}
async function calculate(){clearInvalid();if($('#primeInput').value.trim()!==p)throw Error('p đã thay đổi. Bấm Áp dụng trường trước khi tính.');$('#resultPanel').hidden=true;const expression=$('#expression').value.trim(),snapshotMatrices=structuredClone(matrices),matrix=matrices.find(x=>x.name===$('#leftMatrix').value);const result=await work({action:'calculate',p,matrices:snapshotMatrices,expression,identitySize:matrix.cells.length});last={...result,p,certified:primeCertified,expression,time:new Date().toLocaleTimeString('vi-VN')};history.unshift(last);history=history.slice(0,20);showResult(last);renderHistory();notify('Đã tính xong trên '+fieldLabel(p)+'.');}
function showResult(r){last=r;$('#resultPanel').hidden=false;$('#resultExpression').textContent=r.expression;$('#resultMeta').textContent=fieldLabel(r.p)+(r.kind==='matrix'?' · '+r.value.length+' × '+r.value[0].length:r.kind==='integer'?' · số nguyên':' · phần tử trường');$('#result').innerHTML=r.kind==='matrix'?'<table class="result-table" aria-label="Ma trận kết quả"><tbody>'+r.value.map(row=>'<tr>'+row.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table>':'<div class="scalar-result">'+esc(r.value)+'</div>';
 $('#resultNote').textContent=(r.kind==='integer'?'Hạng là số nguyên thông thường; khi đưa vào ma trận, số đó được chuẩn hóa modulo p. ':'')+(!r.certified?'p đã qua kiểm tra nguyên tố xác suất, chưa được chứng minh nguyên tố. ':'')+(r.p!==p?'Kết quả thuộc trường trước đó. Chuyển lại đúng p để dùng kết quả làm ma trận.':'Kết quả dùng dữ liệu tại thời điểm bấm tính.');for(const id of ['useNew','replaceMatrix'])$('#'+id).disabled=r.p!==p;}
function renderHistory(){$('#historyList').innerHTML=history.length?history.map((r,i)=>`<button data-history="${i}"><span>${esc(r.expression)}</span><small>${esc(fieldLabel(r.p))} · ${r.time}</small></button>`).join(''):'<p>Chưa có phép tính.</p>';}
function resultCells(){if(!last)throw Error('Chưa có kết quả.');if(last.p!==p)throw Error('Kết quả thuộc trường khác.');return last.kind==='matrix'?structuredClone(last.value):[[new Field(p).norm(last.value).toString()]];}
function newName(){const name=names.find(n=>!matrices.some(x=>x.name===n));if(!name)throw Error('Đã dùng tối đa 25 ma trận.');return name;}
async function copy(text){await navigator.clipboard.writeText(text);notify('Đã sao chép.');}
function tsv(cells){return cells.map(r=>r.join('\t')).join('\n');}
function operationExpression(){const a=$('#leftMatrix').value,b=$('#rightMatrix').value,op=$('#operation').value,t=$('#parameter').value.trim();switch(op){case 'add':return a+'+'+b;case 'subtract':return a+'-'+b;case 'multiply':return a+'*'+b;case 'scale':return '('+t+')*'+a;case 'power':if(!/^[+-]?\d+$/.test(t))throw Error('Số mũ phải là số nguyên.');return a+'^('+t+')';case 'commutator':return a+'*'+b+'*'+a+'^-1*'+b+'^-1';case 'kron':case 'had':case 'hcat':case 'vcat':return op+'('+a+','+b+')';case 'sub':return 'sub('+a+','+['fromRow','toRow','fromCol','toCol'].map(id=>$('#'+id).value).join(',')+')';case 'droprow':case 'dropcol':return op+'('+a+','+t+')';default:return op+'('+a+')';}}
function operationUI(){const op=$('#operation').value;$('#rightControl').hidden=!['add','subtract','multiply','kron','had','hcat','vcat','commutator'].includes(op);$('#parameterControl').hidden=!['scale','power','droprow','dropcol'].includes(op);$('#subControls').hidden=op!=='sub';$('#parameterLabel').textContent={scale:'Hệ số c',power:'Số mũ k',droprow:'Dòng cần bỏ',dropcol:'Cột cần bỏ'}[op]||'Tham số';}
$('#operation').onchange=operationUI;
$('#runOperation').onclick=safe(async()=>{$('#expression').value=operationExpression();await calculate();});$('#insertOperation').onclick=safe(()=>{$('#expression').value=operationExpression();$('#expression').focus();});
$('#calculate').onclick=safe(calculate);$('#expression').onkeydown=e=>{if(e.key==='Enter')$('#calculate').click();};$('#cancelJob').onclick=()=>active?.cancel();
$('#primePreset').onchange=()=>{if($('#primePreset').value!=='custom'){$('#primeInput').value=$('#primePreset').value;$('#applyPrime').click();}else $('#primeInput').focus();};
$('#primeInput').oninput=()=>{$('#primePreset').value=['2','3','5','7','11','13','17'].includes($('#primeInput').value.trim())?$('#primeInput').value.trim():'custom';};
$('#applyPrime').onclick=safe(async()=>{clearInvalid();let result;try{result=await work({action:'prime',p:$('#primeInput').value.trim()});}catch(e){$('#primeInput').setAttribute('aria-invalid','true');throw e;}p=result.p;primeCertified=result.certified;$('#primeInput').value=p;$('#fieldLabel').textContent=fieldLabel(p)+' · p = '+p;$('#primeInfo').textContent=(primeCertified?'Đã kiểm tra p nguyên tố xác định.':'p đã qua 32 lượt Miller–Rabin ngẫu nhiên: nguyên tố xác suất, chưa phải chứng minh nguyên tố.')+' Các ô hiện có được giữ nguyên và sẽ tính modulo p mới.';if(last)showResult(last);notify('Đang dùng '+fieldLabel(p)+(primeCertified?'.':' — nguyên tố xác suất.'));});
$('#addMatrix').onclick=safe(()=>{const name=newName();checkInputSize(2,2);snapshot();matrices.push(makeMatrix(name));render();});
$('#undoButton').onclick=()=>{if(undo.length){matrices=undo.pop();render();notify('Đã hoàn tác thay đổi ma trận.');}};
$('#matrixList').addEventListener('focusin',e=>{if(e.target.matches('[data-cell]'))e.target.dataset.before=e.target.value;});
$('#matrixList').addEventListener('input',e=>{const t=e.target;if(t.matches('[data-cell]')){if(t.dataset.recorded!=='1'){snapshot();t.dataset.recorded='1';}matrices.find(x=>x.name===t.dataset.name).cells[+t.dataset.row][+t.dataset.col]=t.value;t.removeAttribute('aria-invalid');}});
$('#matrixList').addEventListener('focusout',e=>{if(e.target.matches('[data-cell]'))delete e.target.dataset.recorded;});
$('#matrixList').addEventListener('keydown',e=>{const t=e.target;if(!t.matches('[data-cell]'))return;let r=+t.dataset.row,c=+t.dataset.col;if(e.key==='Enter'){r++;}else if(e.key==='ArrowUp'){r--;}else if(e.key==='ArrowDown'){r++;}else return;const next=document.querySelector(`[data-cell][data-name="${t.dataset.name}"][data-row="${r}"][data-col="${c}"]`);if(next){e.preventDefault();next.focus();}});
function startPaste(name,text=''){pasteName=name;$('#pasteTitle').textContent='Dán ma trận '+name;$('#pasteText').value=text;$('#pasteError').textContent='';$('#pasteDialog').showModal();$('#pasteText').focus();}
$('#matrixList').addEventListener('paste',e=>{const t=e.target;if(!t.matches('[data-cell]'))return;const text=e.clipboardData.getData('text/plain');if(/[\n\t,;]/.test(text)){e.preventDefault();startPaste(t.dataset.name,text);}});
$('#matrixList').onclick=async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.expr){$('#expression').value=b.dataset.expr;await calculate();return;}const name=b.dataset.name,x=matrices.find(x=>x.name===name);if(!x)return;const action=b.dataset.action,r=x.cells.length,c=x.cells[0].length;if(action==='paste'){startPaste(name);return;}if(action==='copy'){await copy(tsv(x.cells));return;}if(action==='resize'){const nr=Number(document.querySelector(`[data-size="rows"][data-name="${name}"]`).value),nc=Number(document.querySelector(`[data-size="cols"][data-name="${name}"]`).value);checkInputSize(nr,nc,name);snapshot();x.cells=Array.from({length:nr},(_,i)=>Array.from({length:nc},(_,j)=>x.cells[i]?.[j]??'0'));}
 else if(action==='delete'){if(matrices.length===1)return;snapshot();matrices=matrices.filter(m=>m.name!==name);}
 else if(action==='normalize'){const F=new Field(p);const cells=x.cells.map((row,i)=>row.map((v,j)=>{try{return F.parse(v).toString();}catch(e){e.cell={name,row:i,col:j};throw e;}}));snapshot();x.cells=cells;}
 else{if(['identity','invertible'].includes(action)&&r!==c)throw Error('Ma trận đơn vị/khả nghịch cần số dòng bằng số cột.');const F=new Field(p);let cells=Array.from({length:r},(_,i)=>Array.from({length:c},(_,j)=>action==='random'?randomBelow(F.p):action==='identity'||action==='invertible'?(i===j?1n:0n):0n));if(action==='invertible'){for(let k=0;k<r*4;k++){const i=Number(randomBelow(BigInt(r))),j=Number(randomBelow(BigInt(r)));if(i!==j){const a=randomBelow(F.p);cells[i]=cells[i].map((v,t)=>F.norm(v+a*cells[j][t]));}else{const a=1n+randomBelow(F.p-1n);cells[i]=cells[i].map(v=>F.norm(v*a));}}}snapshot();x.cells=cells.map(row=>row.map(String));}render();}catch(e){fail(e);}};
$('#applyPaste').onclick=()=>{try{const text=$('#pasteText').value.trim();if(!text||text.length>500000)throw Error('Dán dữ liệu không rỗng, tối đa 500 KB.');const cells=text.split(/\r?\n/).filter(r=>r.trim()).map(row=>row.trim().split(/[\t,; ]+/));const c=cells[0].length;if(cells.some(row=>row.length!==c))throw Error('Các dòng có số cột khác nhau.');checkInputSize(cells.length,c,pasteName);const F=new Field(p);cells.forEach((row,i)=>row.forEach((v,j)=>{try{F.parse(v);}catch(e){throw Error('Dòng '+(i+1)+', cột '+(j+1)+': '+e.message);}}));snapshot();matrices.find(x=>x.name===pasteName).cells=cells;render();$('#pasteDialog').close();notify('Đã dán ma trận '+pasteName+'.');}catch(e){$('#pasteError').textContent=e.message;}};
$('#closePaste').onclick=()=>$('#pasteDialog').close();$('#helpButton').onclick=()=>$('#helpDialog').showModal();$('#closeHelp').onclick=()=>$('#helpDialog').close();
document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{$('#expression').value=b.dataset.example;$('#expression').focus();});
$('#copyTable').onclick=safe(()=>copy(last.kind==='matrix'?tsv(last.value):last.value));$('#copyLatex').onclick=safe(()=>copy(last.kind==='matrix'?'\\begin{pmatrix}\n'+last.value.map(r=>r.join(' & ')).join(' \\\\\n')+'\n\\end{pmatrix}':last.value));
$('#useNew').onclick=safe(()=>{const cells=resultCells(),name=newName();checkInputSize(cells.length,cells[0].length);snapshot();matrices.push({name,cells});render();notify('Đã tạo ma trận '+name+' từ kết quả.');});
$('#replaceMatrix').onclick=safe(()=>{const cells=resultCells(),name=$('#resultTarget').value;checkInputSize(cells.length,cells[0].length,name);snapshot();matrices.find(x=>x.name===name).cells=cells;render();notify('Đã đưa kết quả vào '+name+'.');});
$('#historyList').onclick=e=>{const b=e.target.closest('[data-history]');if(b){showResult(history[+b.dataset.history]);$('#resultPanel').scrollIntoView({block:'nearest',behavior:'smooth'});}};$('#clearHistory').onclick=()=>{history=[];renderHistory();};
render();operationUI();
