# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
remote_theme: APMatHS/apmaths.github.io
name: "Apmaths"
title: "Apmaths"

  # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://apmaths.github.io" # the base hostname & protocol for your site, e.g. http://example.com
favicon: 'https://i.postimg.cc/RZLKdGYT/CMO777.png'
logo: 'https://i.postimg.cc/RZLKdGYT/CMO777.png'
timezone: 'Asia/Bangkok'

target_blank: false
anchor_link: true
markdown: kramdown
permalink: /blog/:title
paginate: 5 # amount of posts to show
paginate_path: /blog/page/:num/
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
highlighter: rouge
lsi: false
excerpt_separator: <!--more-->
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"

# Build settings
#theme: minima

# Copyright Start Year
copyright: 2023
  prefix: 
  ownership: APMATHS
  link: /

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
