title: APMaths
name: APMaths
author: 
  name: Nam Hoang
description: >
  Tài liệu, bài giảng, công cụ học Toán và các bài viết về
  Giải tích, Đại số, Phương trình vi phân, Xác suất thống kê.

url: https://apmaths.github.io
baseurl: ""

lang: vi
timezone: Asia/Ho_Chi_Minh

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

permalink: /blog/:title

paginate: 10
paginate_path: /blog/page/:num/

# Conversion
highlighter: rouge
lsi: false
excerpt_separator: <!--more-->
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

plugins:
  - search
  - tags:
      tags_file: tags.md
      tags_allowed:
        - Bevel gears
        - Cam contacts
        - Cylindrical gears
        - Developer mode
        - Examples
        - GUI
        - Journal bearings
        - Microsim
        - Piston
        - Rolling contacts
        - Thrust bearings

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

future: false
encoding: utf-8